"""Frozen golden vectors for the cross-repo wire contract.

The robot client (GR00T-WholeBodyControl/psix_wire_contracts.py) vendors a
verbatim copy of psi/src/psi/deploy/wire_contracts.py because the robot env has
no psi checkout. Both repos assert the SAME digests in
``wire_contracts_golden.json`` (this file here; test_hlpwm_wire_vendored.py
there), so silent drift fails a test on whichever side changed.

Regenerate the goldens ONLY together with a *_VERSION bump — never in place:
the digests ARE the contract, and a robot client built against the old vectors
must fail loudly, not hash differently.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from psi.deploy.wire_contracts import (
    CONDITION_HASH_VERSION,
    CONDITION_SCHEMA_VERSION,
    condition_hash,
)

_GOLDEN = json.loads((Path(__file__).parent / "wire_contracts_golden.json").read_text())


def _goal_for(shape: list[int], rng: np.random.Generator) -> np.ndarray:
    if shape[0] == 0:
        return np.zeros(shape, np.uint8)
    return rng.integers(0, 256, size=tuple(shape), dtype=np.uint8)


def test_versions_pinned():
    assert _GOLDEN["hash_version"] == CONDITION_HASH_VERSION
    assert _GOLDEN["schema_version"] == CONDITION_SCHEMA_VERSION


def test_condition_hash_golden_vectors():
    # One shared rng in file order: the vectors were generated by a single pass,
    # so draw order is part of the fixture.
    rng = np.random.default_rng(_GOLDEN["generator_seed"])
    for vec in _GOLDEN["vectors"]:
        goal = _goal_for(vec["shape"], rng)
        assert condition_hash(vec["instruction"], goal) == vec["digest"], (
            f"condition_hash drifted for vector {vec['name']!r}: the wire "
            "contract is no longer byte-identical to the frozen goldens. If the "
            "change is intentional, bump CONDITION_HASH_VERSION and regenerate "
            "the goldens on BOTH repos (see module docstring)."
        )


if __name__ == "__main__":
    # Executed directly by scripts/deploy/smoke_deploy_config.sh, which cannot
    # assume pytest exists in the robot-side venv. Without this the gate ran the
    # file as a script, defined the tests, and exited 0 on ANY drift.
    test_versions_pinned()
    test_condition_hash_golden_vectors()
    print("wire-contract goldens OK")
